# Generated by Django 2.0.1 on 2018-02-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=60)),
                ('location', models.CharField(blank=True, max_length=60)),
                ('degree', models.CharField(blank=True, max_length=60)),
                ('major', models.CharField(blank=True, max_length=60)),
                ('gpa', models.FloatField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
